### ISSUE TITLE
tox -e genconfig 在有代理下報錯

### ISSUE THREAD

**Issue by huliangfei** [huliangfei/kolla-ansible-doc-zh_cn#6]
[root@manage01 kolla]# tox -e genconfig
genconfig create: /root/kolla/.tox/genconfig
genconfig installdeps: -r/root/kolla/requirements.txt, -r/root/kolla/test-requirements.txt
ERROR: invocation failed (exit code 2), logfile: /root/kolla/.tox/genconfig/log/genconfig-1.log
ERROR: actionid: genconfig
msg: getenv
cmdargs: ['/root/kolla/.tox/genconfig/bin/pip', 'install', '-chttps://git.openstack.org/cgit/openstack/requirements/plain/upper-constraints.txt?h=stable/pike', '-r/root/kolla/requirements.txt', '-r/root/kolla/test-requirements.txt']

Exception:
Traceback (most recent call last):
  File "/root/kolla/.tox/genconfig/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/root/kolla/.tox/genconfig/lib/python2.7/site-packages/pip/commands/install.py", line 312, in run
    wheel_cache
  File "/root/kolla/.tox/genconfig/lib/python2.7/site-packages/pip/basecommand.py", line 269, in populate_requirement_set
    session=session, wheel_cache=wheel_cache):
  File "/root/kolla/.tox/genconfig/lib/python2.7/site-packages/pip/req/req_file.py", line 84, in parse_requirements
    filename, comes_from=comes_from, session=session
  File "/root/kolla/.tox/genconfig/lib/python2.7/site-packages/pip/download.py", line 417, in get_file_content
    resp = session.get(url)
  File "/root/kolla/.tox/genconfig/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 488, in get
    return self.request('GET', url, **kwargs)
  File "/root/kolla/.tox/genconfig/lib/python2.7/site-packages/pip/download.py", line 386, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/root/kolla/.tox/genconfig/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/kolla/.tox/genconfig/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/root/kolla/.tox/genconfig/lib/python2.7/site-packages/pip/_vendor/cachecontrol/adapter.py", line 47, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/root/kolla/.tox/genconfig/lib/python2.7/site-packages/pip/_vendor/requests/adapters.py", line 390, in send
    conn = self.get_connection(request.url, proxies)
  File "/root/kolla/.tox/genconfig/lib/python2.7/site-packages/pip/_vendor/requests/adapters.py", line 290, in get_connection
    proxy_manager = self.proxy_manager_for(proxy)
  File "/root/kolla/.tox/genconfig/lib/python2.7/site-packages/pip/_vendor/requests/adapters.py", line 194, in proxy_manager_for
    **proxy_kwargs)
  File "/root/kolla/.tox/genconfig/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/poolmanager.py", line 367, in proxy_from_url
    return ProxyManager(proxy_url=url, **kw)
  File "/root/kolla/.tox/genconfig/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/poolmanager.py", line 318, in __init__
    raise ProxySchemeUnknown(proxy.scheme)
ProxySchemeUnknown: Not supported proxy scheme f1225721

ERROR: could not install deps [-r/root/kolla/requirements.txt, -r/root/kolla/test-requirements.txt]; v = InvocationError('/root/kolla/.tox/genconfig/bin/pip install -chttps://git.openstack.org/cgit/openstack/requirements/plain/upper-constraints.txt?h=stable/pike -r/root/kolla/requirements.txt -r/root/kolla/test-requirements.txt (see /root/kolla/.tox/genconfig/log/genconfig-1.log)', 2)
_____________________________________________________________________________________ summary _____________________________________________________________________________________
ERROR:   genconfig: could not install deps [-r/root/kolla/requirements.txt, -r/root/kolla/test-requirements.txt]; v = InvocationError('/root/kolla/.tox/genconfig/bin/pip install -chttps://git.openstack.org/cgit/openstack/requirements/plain/upper-constraints.txt?h=stable/pike -r/root/kolla/requirements.txt -r/root/kolla/test-requirements.txt (see /root/kolla/.tox/genconfig/log/genconfig-1.log)', 2)

**Comment by huliangfei** [comment]
原因：https 代理配置錯誤，重新配置即OK
